version: '3.9'

services:

 web:
  build:
    context: .
  restart: always
  ports:
    - "5000:5000"
  volumes:
    - ./:/app
  environment:
    FLASK_ENV: development
  # networks:
  #   - backnet
  #   - frontnet

#  proxy:
#   build: proxy
#   restart: always
#   ports:
#     - 80:80
#   networks:
#     - frontnet

# networks:
#   backnet:
#   frontnet:
